package com.bw.homework.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.homework.MyEntity;

import com.bw.homework.greendao.MyEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myEntityDaoConfig;

    private final MyEntityDao myEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myEntityDaoConfig = daoConfigMap.get(MyEntityDao.class).clone();
        myEntityDaoConfig.initIdentityScope(type);

        myEntityDao = new MyEntityDao(myEntityDaoConfig, this);

        registerDao(MyEntity.class, myEntityDao);
    }
    
    public void clear() {
        myEntityDaoConfig.clearIdentityScope();
    }

    public MyEntityDao getMyEntityDao() {
        return myEntityDao;
    }

}
